### ISSUE TITLE
Task 3: 5의 배수 검사

### ISSUE THREAD

**Issue by Shsin9797** [KaTeCam-BE-4/team-fizzbuzz#4]
## Description

반복문 내에서 현재 숫자가 5의 배수인지 확인하는 조건문을 작성합니다.
5의 배수일 경우 "Buzz"를 출력하도록 합니다.

## Tasks
- [x] Buzz 클래스 구현 
    - [x] 현재 숫자가 5의 배수인지 확인하는 조건문 작성
    - [x] 5의 배수인경우 Buzz 출력
